import { CONFIG } from './config';

export const STYLES = {
  container: {
    position: 'relative',
    width: '100vw',
    height: '100vh',
    backgroundColor: CONFIG.theme.bg,
    color: CONFIG.theme.text,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    overflow: 'hidden',
  },
  canvas: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    pointerEvents: 'none',
    zIndex: 20,
  },
  topLeft: {
    position: 'absolute',
    top: '40px',
    left: '40px',
    zIndex: 7,
    pointerEvents: 'none',
  },
  nameLabel: {
    fontSize: '50px',
    fontWeight: 400,
    letterSpacing: '0.01em',
    lineHeight: 1.1,
  },
  roleLabel: {
    fontSize: '40px',
    fontWeight: 300,
    opacity: 0.5,
    lineHeight: 1.1,
  },
  navDot: {
    position: 'absolute',
    top: '40px',
    right: '40px',
    width: '16px',
    height: '16px',
    borderRadius: '50%',
    backgroundColor: CONFIG.theme.text,
    opacity: 1,
    cursor: 'pointer',
    zIndex: 10,
    transition: 'transform 0.3s ease, opacity 0.3s ease',
    border: 'none',
    padding: 0,
    outline: 'none',
  },
  backdrop: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(26, 26, 26, 0.08)',
    zIndex: 4,
    transition: 'opacity 450ms ease',
  },
  panel: {
    position: 'fixed',
    top: 0,
    right: 0,
    width: '28vw',
    minWidth: '320px',
    height: '100%',
    backgroundColor: CONFIG.theme.panelBg,
    color: CONFIG.theme.panelText,
    zIndex: 5,
    transition: 'transform 450ms cubic-bezier(0.25, 0.1, 0.25, 1)',
    overflowY: 'auto',
  },
  panelInner: {
    padding: '60px 40px',
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100%',
  },
  closeDot: {
    position: 'fixed',
    top: '40px',
    right: 'calc(28vw + 40px)',
    width: '16px',
    height: '16px',
    borderRadius: '50%',
    backgroundColor: CONFIG.theme.text,
    cursor: 'pointer',
    zIndex: 10,
    border: 'none',
    padding: 0,
    outline: 'none',
  },
  panelName: {
    fontSize: '28px',
    fontWeight: 400,
    marginBottom: '6px',
  },
  panelBio: {
    fontSize: '16px',
    fontWeight: 400,
    lineHeight: 1.7,
    marginTop: '0',
    whiteSpace: 'pre-line',
  },
  panelBottom: {
    marginTop: 'auto',
  },
  sectionTitle: {
    fontSize: '12px',
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '0.15em',
    opacity: 0.3,
    marginBottom: '20px',
  },
  projectItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '14px 0',
    borderBottom: '1px solid rgba(26, 26, 26, 0.08)',
  },
  projectTitle: {
    fontSize: '16px',
    fontWeight: 400,
  },
  projectTags: {
    fontSize: '13px',
    fontWeight: 300,
    opacity: 0.4,
  },
  contactSection: {
    marginTop: '48px',
  },
  contactLink: {
    display: 'block',
    fontSize: '16px',
    fontWeight: 400,
    color: CONFIG.theme.panelText,
    textDecoration: 'none',
    padding: '10px 0',
    opacity: 1,
    transition: 'opacity 0.2s ease',
  },
};
